trigger:
  branches:
    include:
      - main
      - develop

pool:
  vmImage: 'ubuntu-latest'
  
variables:
  system.debug: true
  buildConfiguration: 'Release'
  acrName: 'libreborrcontainers'  # Zameni sa imenom svog ACR-a
  apiImage1: 'libreborr-web'
  apiImage2: 'libreborr-fetchbookapi'
  imageTag: '$(Build.BuildId)'  # Jedinstveni tag za svaku izgradnju

steps:
  - checkout: self
    persistCredentials: true
    clean: true
    
  # Pull ASP.NET image first
  - script: |
      docker pull mcr.microsoft.com/dotnet/aspnet:9.0
    displayName: 'Pull ASP.NET Docker Image'
      
  - task: UseDotNet@2
    inputs:
      packageType: 'sdk'
      version: '9.x'
      includePreviewVersions: true

  - task: DotNetCoreCLI@2
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      arguments: '--no-cache'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      arguments: '--configuration $(buildConfiguration)'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    inputs:
      command: 'test'
      arguments: '--configuration $(buildConfiguration) --no-build'
      projects: '**/*.csproj'

  - task: PublishBuildArtifacts@1
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'drop'
      
  - script: |
      echo "Listing all .csproj files:"
      find $(Build.SourcesDirectory) -name "*.csproj"
    displayName: 'Find all .csproj files'

  # Docker login to ACR
  - task: Docker@2
    inputs:
      command: 'login'
      containerRegistry: '$(acrName).azurecr.io'
      azureSubscription: 'libreborrcontainers'  # Zameni sa nazivom svoje Azure pretplate
  - script: |
      export DOCKER_BUILDKIT=0
    displayName: 'Build Docker Image with BuildKit Disabled'
  # Build and push API 1 Docker image
  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      repository: '$(acrName).azurecr.io/$(apiImage1)'
      tags: '$(imageTag)'
      dockerfile: '$(Build.SourcesDirectory)/LibreBorr.Web/Dockerfile'  # Putanja do Dockerfile-a za prvi API
      context: '$(Build.SourcesDirectory)'
      containerRegistry: '$(acrName).azurecr.io'
      arguments: '--platform linux/amd64'

  # Build and push API 2 Docker image
  - task: Docker@2
    inputs:
      command: 'buildAndPush'
      repository: '$(acrName).azurecr.io/$(apiImage2)'
      tags: '$(imageTag)'
      dockerfile: $(Build.SourcesDirectory)/LibreBorr.FetchBookApi/Dockerfile  # Putanja do Dockerfile-a za drugi API
      context: $(Build.SourcesDirectory)
      containerRegistry: '$(acrName).azurecr.io'
      arguments: '--platform linux/amd64'
